PREFIX ?= /usr/local
BINARY = apfel
VERSION_FILE = .version

.PHONY: build install uninstall clean bump-patch bump-minor bump-major generate-build-info update-readme version release-minor release-major

# --- Build (auto-bumps patch) ---

build: bump-patch generate-build-info update-readme
	swift build -c release

install: build
	@pkill -f "apfel --serve" 2>/dev/null || true
	@pkill -f "apfel --gui" 2>/dev/null || true
	@sleep 1
	@if [ -w "$(PREFIX)/bin" ]; then \
		install .build/release/$(BINARY) $(PREFIX)/bin/$(BINARY); \
	else \
		sudo install .build/release/$(BINARY) $(PREFIX)/bin/$(BINARY); \
	fi
	@echo "✓ installed: $$($(PREFIX)/bin/$(BINARY) --version)"

# --- Version bumps ---

bump-patch:
	@v=$$(cat $(VERSION_FILE)); \
	major=$$(echo $$v | cut -d. -f1); \
	minor=$$(echo $$v | cut -d. -f2); \
	patch=$$(echo $$v | cut -d. -f3); \
	new="$$major.$$minor.$$((patch+1))"; \
	echo "$$new" > $(VERSION_FILE); \
	echo "$$v → $$new"

bump-minor:
	@v=$$(cat $(VERSION_FILE)); \
	major=$$(echo $$v | cut -d. -f1); \
	minor=$$(echo $$v | cut -d. -f2); \
	new="$$major.$$((minor+1)).0"; \
	echo "$$new" > $(VERSION_FILE); \
	echo "$$v → $$new"

bump-major:
	@v=$$(cat $(VERSION_FILE)); \
	major=$$(echo $$v | cut -d. -f1); \
	new="$$((major+1)).0.0"; \
	echo "$$new" > $(VERSION_FILE); \
	echo "$$v → $$new"

# --- Release targets (bump without extra patch increment) ---

release-minor: bump-minor generate-build-info update-readme
	swift build -c release

release-major: bump-major generate-build-info update-readme
	swift build -c release

# --- Generated files ---

generate-build-info:
	@v=$$(cat $(VERSION_FILE)); \
	commit=$$(git rev-parse --short HEAD 2>/dev/null || echo "unknown"); \
	branch=$$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown"); \
	date=$$(date -u +"%Y-%m-%d %H:%M:%S UTC"); \
	swift_ver=$$(swift --version 2>/dev/null | head -1 | sed 's/.*version //' | sed 's/ .*//'); \
	os_ver=$$(sw_vers -productVersion 2>/dev/null || echo "unknown"); \
	echo "// Auto-generated by make — do not edit" > Sources/BuildInfo.swift; \
	echo "let buildVersion = \"$$v\"" >> Sources/BuildInfo.swift; \
	echo "let buildCommit = \"$$commit\"" >> Sources/BuildInfo.swift; \
	echo "let buildBranch = \"$$branch\"" >> Sources/BuildInfo.swift; \
	echo "let buildDate = \"$$date\"" >> Sources/BuildInfo.swift; \
	echo "let buildSwiftVersion = \"$$swift_ver\"" >> Sources/BuildInfo.swift; \
	echo "let buildOS = \"macOS $$os_ver\"" >> Sources/BuildInfo.swift

update-readme:
	@v=$$(cat $(VERSION_FILE)); \
	sed -i '' 's/Version [0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*/Version '"$$v"'/' README.md; \
	sed -i '' 's/version-[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*-blue/version-'"$$v"'-blue/' README.md

# --- Utilities ---

version:
	@cat $(VERSION_FILE)

uninstall:
	@if [ -w "$(PREFIX)/bin" ]; then \
		rm -f $(PREFIX)/bin/$(BINARY); \
	else \
		sudo rm -f $(PREFIX)/bin/$(BINARY); \
	fi

clean:
	swift package clean
