// Auto-generated by make — do not edit
let buildVersion = "1.11.0"
let buildCommit = "791ca79"
let buildBranch = "main"
let buildDate = "2026-09-19 14:01:11 UTC"
let buildSwiftVersion = "6.3.3"
let buildOS = "macOS 26.5.2"
