// Auto-generated by make — do not edit
let buildVersion = "1.16.0"
let buildCommit = "4651c7b"
let buildBranch = "main"
let buildDate = "2026-10-05 19:45:37 UTC"
let buildSwiftVersion = "6.4"
let buildOS = "macOS 27.0.1"
