// Auto-generated by make — do not edit
let buildVersion = "1.12.0"
let buildCommit = "9c7d6e5"
let buildBranch = "main"
let buildDate = "2026-09-24 17:48:55 UTC"
let buildSwiftVersion = "6.3.3"
let buildOS = "macOS 26.5.2"
